<a href="https://colab.research.google.com/github/sam-1141/Exploratory-Data-Analysis/blob/main/FLIGFHT_PRICE_PREDICTON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
train_path = "/content/drive/MyDrive/Data_Sets/Data_Train.xlsx"
test_path = "/content/drive/MyDrive/Data_Sets/Test_set.xlsx"

In [ ]:
train_df = pd.read_excel(train_path)
test_df = pd.read_excel(test_path)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [ ]:
train_df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          2671 non-null   object
 1   Date_of_Journey  2671 non-null   object
 2   Source           2671 non-null   object
 3   Destination      2671 non-null   object
 4   Route            2671 non-null   object
 5   Dep_Time         2671 non-null   object
 6   Arrival_Time     2671 non-null   object
 7   Duration         2671 non-null   object
 8   Total_Stops      2671 non-null   object
 9   Additional_Info  2671 non-null   object
dtypes: object(10)
memory usage: 208.8+ KB

In [ ]:
final_df = pd.concat([train_df, test_df], ignore_index=True)

In [ ]:
final_df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0
...,...,...,...,...,...,...,...,...,...,...,...
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

### Feature Engineering

In [ ]:
final_df.drop(['Date_of_Journey','MOnth'], axis=1, inplace=True)

In [ ]:
final_df['Date'] = final_df['Date'].astype(int)
final_df['Month'] = final_df['Month'].astype(int)
final_df['Year'] = final_df['Year'].astype(int)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Year             13354 non-null  int64
 12  Month            13354 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.3+ MB

In [ ]:
final_df.dropna(inplace=True)

final_df.isnull().sum()

Airline            0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
Date               0
Year               0
Month              0
dtype: int64

In [ ]:
final_df

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Year,Month
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,2019,3
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,2019,5
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,2019,6
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,2019,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,2019,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107.0,9,2019,4
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145.0,27,2019,4
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229.0,27,2019,4
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648.0,1,2019,3
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753.0,9,2019,5

In [ ]:
rows_with_value = final_df[final_df.eq('8h 20m').any(axis=1)]
rows_with_value.size[0]

TypeError: 'int' object is not subscriptable

In [ ]:
final_df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Date', 'Year',
       'Month'],
      dtype='object')

In [ ]:
final_df['Arrival_Time']

0        01:10
1        13:15
2        04:25
3        23:30
4        21:35
         ...
10678    22:25
10679    23:20
10680    11:20
10681    14:10
10682    19:15
Name: Arrival_Time, Length: 10682, dtype: object

In [ ]:
final_df['Hour']=final_df['Arrival_Time'].apply(lambda x: x.split(':')[0])

In [ ]:
final_df['Minute']=final_df['Arrival_Time'].apply(lambda x: x.split(':')[1])

In [ ]:
final_df.drop('Arrival_Time', axis=1,inplace=True)

In [ ]:
final_df.info(

)

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Duration         10682 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10682 non-null  object
 8   Price            10682 non-null  float64
 9   Date             10682 non-null  int64
 10  Year             10682 non-null  int64
 11  Month            10682 non-null  int64
 12  Hour             10682 non-null  object
 13  Minute           10682 non-null  object
dtypes: float64(1), int64(3), object(10)
memory usage: 1.5+ MB

In [ ]:
final_df['Hour']=final_df['Hour'].astype(int)
final_df['Minute']=final_df['Minute'].astype(int)

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Duration         10682 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10682 non-null  object
 8   Price            10682 non-null  float64
 9   Date             10682 non-null  int64
 10  Year             10682 non-null  int64
 11  Month            10682 non-null  int64
 12  Hour             10682 non-null  int64
 13  Minute           10682 non-null  int64
dtypes: float64(1), int64(5), object(8)
memory usage: 1.5+ MB

In [ ]:
final_df['DEP_Hour']=final_df['Dep_Time'].apply(lambda x: x.split(':')[0]).astype(int)
final_df['DEP_Minute']=final_df['Dep_Time'].apply(lambda x: x.split(':')[1]).astype(int)

In [ ]:
final_df.drop('Dep_Time', axis=1,inplace=True)

In [ ]:
final_df.info(

)

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  float64
 8   Date             10682 non-null  int64
 9   Year             10682 non-null  int64
 10  Month            10682 non-null  int64
 11  Hour             10682 non-null  int64
 12  Minute           10682 non-null  int64
 13  DEP_Hour         10682 non-null  int64
 14  DEP_Minute       10682 non-null  int64
dtypes: float64(1), int64(7), object(7)
memory usage: 1.6+ MB

In [ ]:
final_df['Total_Stops']=train_df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, '4 stops':4})

In [ ]:
final_df.drop('Route',axis =1, inplace = True)

In [ ]:
final_df['Total_Stops'] = final_df['Total_Stops'].astype(np.int32)

In [ ]:
final_df['Total_Stops']

0        0
1        2
2        2
3        1
4        1
        ..
10678    0
10679    0
10680    0
10681    0
10682    2
Name: Total_Stops, Length: 10682, dtype: int32

In [ ]:
final_df['Duration']

0        2h 50m
1        7h 25m
2           19h
3        5h 25m
4        4h 45m
          ...
10678    2h 30m
10679    2h 35m
10680        3h
10681    2h 40m
10682    8h 20m
Name: Duration, Length: 10682, dtype: object

In [ ]:
import re

def convert_to_minutes(time_str):
    # Extract hours and minutes using regex
    hours = 0
    minutes = 0

    # Search for hours (e.g., '3h' or '2h')
    hours_match = re.search(r'(\d+)h', time_str)
    if hours_match:
        hours = int(hours_match.group(1))

    # Search for minutes (e.g., '40m')
    minutes_match = re.search(r'(\d+)m', time_str)
    if minutes_match:
        minutes = int(minutes_match.group(1))

    total_minutes = hours * 60 + minutes
    return total_minutes

In [ ]:
final_df['Duration'] = final_df['Duration'].apply(lambda x: convert_to_minutes(x))

In [ ]:
final_df['Duration'].astype(np.int32)

0         170
1         445
2        1140
3         325
4         285
         ...
10678     150
10679     155
10680     180
10681     160
10682     500
Name: Duration, Length: 10682, dtype: int32

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [ ]:
final_df['Airline'] = label_encoder.fit_transform(final_df['Airline'])

In [ ]:
final_df['Airline'].info(

)

<class 'pandas.core.series.Series'>
Index: 10682 entries, 0 to 10682
Series name: Airline
Non-Null Count  Dtype
--------------  -----
10682 non-null  int64
dtypes: int64(1)
memory usage: 424.9 KB

In [ ]:
final_df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Additional_Info',
       'Price', 'Date', 'Year', 'Month', 'Hour', 'Minute', 'DEP_Hour',
       'DEP_Minute', 'Total_Stops'],
      dtype='object')

In [ ]:
final_df['Additional_Info'] = label_encoder.fit_transform(final_df['Additional_Info'])
final_df['Source'] = label_encoder.fit_transform(final_df['Source'])
final_df['Destination'] = label_encoder.fit_transform(final_df['Destination'])

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  int64
 1   Source           10682 non-null  int64
 2   Destination      10682 non-null  int64
 3   Duration         10682 non-null  int64
 4   Additional_Info  10682 non-null  int64
 5   Price            10682 non-null  float64
 6   Date             10682 non-null  int64
 7   Year             10682 non-null  int64
 8   Month            10682 non-null  int64
 9   Hour             10682 non-null  int64
 10  Minute           10682 non-null  int64
 11  DEP_Hour         10682 non-null  int64
 12  DEP_Minute       10682 non-null  int64
 13  Total_Stops      10682 non-null  int32
dtypes: float64(1), int32(1), int64(12)
memory usage: 1.4 MB

In [ ]:
X=final_df.drop('Price', axis=1)
y=final_df['Price']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [ ]:
lin_reg_params = {
    "fit_intercept": True,  # Whether to calculate the intercept
    "copy_X": True,         # Whether to copy X or overwrite
    "n_jobs": -1,         # Parallel jobs for computation
    "positive": False       # Force coefficients to be positive
}

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
# Pipeline: Scaling + Linear Regression
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("linreg", LinearRegression(fit_intercept=True))
])

# Train
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('linreg', LinearRegression())])

In [ ]:
# 📌 6. Evaluate Model

# Train
pipeline.fit(X_train, y_train)

# Predict
y_pred = pipeline.predict(X_test)

# Evaluation
print("Intercept:", pipeline.named_steps["linreg"].intercept_)
print("Coefficients:", pipeline.named_steps["linreg"].coef_)
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

Intercept: 9078.336688121708
Coefficients: [ 4.40005775e+02 -2.96980171e+02  1.57572038e+02  5.82334870e+02
  8.79106965e+00 -6.60369987e+02 -1.70530257e-13 -5.82198687e+02
 -2.54740688e+01 -1.23394331e+02  2.55208060e+02 -1.60798694e+02
  2.58400757e+03]
MSE: 12116844.37766856
RMSE: 3480.9257931861403
MAE: 2448.3049787665036
R² Score: 0.43804782830055067

In [ ]:
import sklearn.linear_model
print([cls for cls in dir(sklearn.linear_model) if not cls.startswith("_")])

['ARDRegression', 'BayesianRidge', 'ElasticNet', 'ElasticNetCV', 'GammaRegressor', 'HuberRegressor', 'Lars', 'LarsCV', 'Lasso', 'LassoCV', 'LassoLars', 'LassoLarsCV', 'LassoLarsIC', 'LinearRegression', 'LogisticRegression', 'LogisticRegressionCV', 'MultiTaskElasticNet', 'MultiTaskElasticNetCV', 'MultiTaskLasso', 'MultiTaskLassoCV', 'OrthogonalMatchingPursuit', 'OrthogonalMatchingPursuitCV', 'PassiveAggressiveClassifier', 'PassiveAggressiveRegressor', 'Perceptron', 'PoissonRegressor', 'QuantileRegressor', 'RANSACRegressor', 'Ridge', 'RidgeCV', 'RidgeClassifier', 'RidgeClassifierCV', 'SGDClassifier', 'SGDOneClassSVM', 'SGDRegressor', 'TheilSenRegressor', 'TweedieRegressor', 'enet_path', 'lars_path', 'lars_path_gram', 'lasso_path', 'orthogonal_mp', 'orthogonal_mp_gram', 'ridge_regression']

In [ ]:
dir(sklearn.linear_model)

['ARDRegression',
 'BayesianRidge',
 'ElasticNet',
 'ElasticNetCV',
 'GammaRegressor',
 'HuberRegressor',
 'Lars',
 'LarsCV',
 'Lasso',
 'LassoCV',
 'LassoLars',
 'LassoLarsCV',
 'LassoLarsIC',
 'LinearRegression',
 'LogisticRegression',
 'LogisticRegressionCV',
 'MultiTaskElasticNet',
 'MultiTaskElasticNetCV',
 'MultiTaskLasso',
 'MultiTaskLassoCV',
 'OrthogonalMatchingPursuit',
 'OrthogonalMatchingPursuitCV',
 'PassiveAggressiveClassifier',
 'PassiveAggressiveRegressor',
 'Perceptron',
 'PoissonRegressor',
 'QuantileRegressor',
 'RANSACRegressor',
 'Ridge',
 'RidgeCV',
 'RidgeClassifier',
 'RidgeClassifierCV',
 'SGDClassifier',
 'SGDOneClassSVM',
 'SGDRegressor',
 'TheilSenRegressor',
 'TweedieRegressor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_bayes',
 '_cd_fast',
 '_coordinate_descent',
 '_glm',
 '_huber',
 '_least_angle',
 '_linear_loss',
 '_logistic',
 '_omp',
 '_passive_aggressive',
 '_perceptron',
 '_quantile',
 '_ransac',
 '_ridge',
 '_sag',
 '_sag_fast',
 '_sgd_fast',
 '_stochastic_gradient',
 '_theil_sen',
 'enet_path',
 'lars_path',
 'lars_path_gram',
 'lasso_path',
 'orthogonal_mp',
 'orthogonal_mp_gram',
 'ridge_regression']